# reboot_fire_and_exit.yml
---
- name: Trigger a reboot and exit immediately
  hosts: all
  gather_facts: false
  become: true
  any_errors_fatal: true

  vars:
    # Give SSH a moment to ack before the host kills the session
    reboot_ack_delay_seconds: 3

  tasks:
    - name: Initiate reboot without waiting
      ansible.builtin.shell: |
        nohup bash -c 'sleep {{ reboot_ack_delay_seconds }}; \
          (command -v shutdown >/dev/null && shutdown -r now) || \
          (command -v systemctl >/dev/null && systemctl reboot) || \
          reboot' >/dev/null 2>&1 &
      args:
        executable: /bin/bash
      changed_when: true

    - name: Stop the play after triggering reboot
      ansible.builtin.meta: end_play
