# pb_render.yml
- name: Render config via Python (preview only, no device changes)
  hosts: "{{ my_playbook_hosts | default('all') }}"
  gather_facts: false

  vars:
    # --- DB ---
    mysql_host: "pma.fritz.lan"
    mysql_port: 3306
    mysql_db: "netvars"
    mysql_user: "ansible"
    mysql_password: "ChangeMe"
    db_name: "netvars"

    # --- Paths on controller ---
    work_dir: "{{ playbook_dir }}"
    renderer_src: "python-script/render_from_mysql.py"   
    render_dir: "{{ work_dir }}/rendered-config"
    render_out: "{{ render_dir }}/{{ inventory_hostname }}.cfg"

  tasks:
    - name: Ensure work and rendered-config directories exist (controller)
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ work_dir }}"
        - "{{ render_dir }}"
      delegate_to: localhost

    #- name: Ensure renderer script is present (controller)
    #  copy:
    #    src: "{{ renderer_src }}"
    #    dest: "{{ renderer_dest }}"
    #    mode: "0755"
    #  delegate_to: localhost

    - name: Render and preview (first 300 chars), save to rendered-config/
      command: >
        python3 {{ renderer_src }}
        --host {{ inventory_hostname }}
        --mysql-host {{ mysql_host }}
        --mysql-port {{ mysql_port }}
        --mysql-db {{ mysql_db }}
        --mysql-user {{ mysql_user }}
        --mysql-password {{ mysql_password }}
        --db-name {{ db_name }}
        {% if template_name is defined and template_name|length > 0 %}--template-name "{{ template_name }}"{% endif %}
        --write-to {{ render_out }}
        --preview 300
        --fail-on-unresolved
      register: render_rs
      changed_when: false
      delegate_to: localhost

    #- name: Show render preview
    #  debug:
    #    var: render_rs.stdout
    #  delegate_to: localhost

