# send_deployment_done_mail.yml
---
- name: Send email
  hosts: localhost

  vars:
    mail_to: "admin@home.com"
    mail_subject: "Deployment finished"
    mail_body: "deployment finished"
    mail_from: "ansible@home.com"
    # smtp_host: smtp.example.com
    # smtp_port: 587
    # smtp_username: 'myuser@example.com'
    # smtp_password: "mypassword"
  tasks:
    - name: Send mail
      mail:
        to: "{{ mail_to }}"
        subject: "{{ mail_subject }}"
        from: "{{ mail_from }}"
        # host: "{{ smtp_host | default(omit) }}"
        # port: "{{ smtp_port | default(omit) }}"
        # username: "{{ smtp_username | default(omit) }}"
        # password: "{{ smtp_password | default(omit) }}"
        # secure: "{{ smtp_secure | default(omit) }}"
        body: |
          <html>
          <body style="font-family: Arial, sans-serif; color: #333;">
            <h2>✅ Playbook Report</h2>
            
            <p>playbook reported: <br> "{{ mail_body }}"</p>
            <p style="font-size: 12px; color: #888;">
              Sent by Ansible at {{ ansible_date_time.iso8601 }}
            </p>
          </body>
          </html>          
      delegate_to: localhost
      run_once: true
