---
- name: Send monitoring info to Prometheus Pushgateway
  hosts: localhost
  gather_facts: false
  vars:
    pushgateway_url: "http://pushgateway.example.lan:9091"   # your Pushgateway
    job_name: "ansible_reboot"
    instance: "{{ inventory_hostname }}"
    metric_value: 1   # set 1 for success, 0 for failure

  tasks:
    - name: Format Prometheus metrics
      copy:
        dest: /tmp/metrics.prom
        content: |
          # TYPE ansible_job_success gauge
          ansible_job_success{job="{{ job_name }}",instance="{{ instance }}"} {{ metric_value }}

    - name: Push metrics to Pushgateway
      uri:
        url: "{{ pushgateway_url }}/metrics/job/{{ job_name }}/instance/{{ instance }}"
        method: POST
        body: "{{ lookup('file', '/tmp/metrics.prom') }}"
        status_code: 202
