# send_deployment_done_mail.yml
---
- name: Send deployment completion email
  hosts: all
  gather_facts: false

  vars:
    mail_to: "admin@home.com"
    mail_subject: "Deployment finished"
    mail_body: "deployment finished"
    mail_from: "ansible@home.com"

    # If you don't have a local MTA, uncomment and fill these SMTP settings:
    # smtp_host: "smtp.home.com"
    # smtp_port: 587
    # smtp_username: "smtp-user"
    # smtp_password: "smtp-pass"
    # smtp_secure: "starttls"   # options: never | starttls | always

  tasks:
    - name: Send mail
      ansible.builtin.mail:
        to: "{{ mail_to }}"
        subject: "{{ mail_subject }}"
        body: "{{ mail_body }}"
        from: "{{ mail_from }}"
        # host: "{{ smtp_host | default(omit) }}"
        # port: "{{ smtp_port | default(omit) }}"
        # username: "{{ smtp_username | default(omit) }}"
        # password: "{{ smtp_password | default(omit) }}"
        # secure: "{{ smtp_secure | default(omit) }}"
      delegate_to: localhost
      run_once: true
