# wait_until_reachable.yml
---
- name: Wait for host reachability (fails after timeout)
  hosts: all
  gather_facts: false
  any_errors_fatal: true

  vars:
    wait_timeout_seconds: 600   # 10 minutes
    initial_delay: 0            # start checking immediately
    poll_interval: 5            # seconds between checks

  tasks:
    - name: Wait for SSH to become reachable (max {{ wait_timeout_seconds }}s)
      ansible.builtin.wait_for_connection:
        timeout: "{{ wait_timeout_seconds }}"
        delay: "{{ initial_delay }}"
        sleep: "{{ poll_interval }}"

    - name: Confirm success
      ansible.builtin.debug:
        msg: "Host {{ inventory_hostname }} is reachable."
